import { Schema } from 'effect';

// Generated schemas for data validation in data.proto
// Source: /Users/nataliai/Projects/test/effect/src/proto/data.proto
// Generated on: 2025-10-05T19:36:59.728Z
// 
// This file includes custom validation for data structure where arrayItems.data.items cannot be empty.
// DO NOT EDIT THIS FILE MANUALLY - it will be regenerated on build.

// Enhanced schema for data structure validation
// This validates the entire data object structure: data.{key}.arrayItems.data.items cannot be empty
export const DataSchema = Schema.Record({
  key: Schema.String,
  value: Schema.Struct({
    arrayItems: Schema.optional(Schema.Struct({
      data: Schema.optional(Schema.Struct({
        items: Schema.Record({
          key: Schema.String,
          value: Schema.Unknown
        }).pipe(Schema.filter((record) => Object.keys(record).length > 0, {
          message: () => "arrayItems.data.items cannot be empty"
        }))
      }))
    }))
  })
});

export type Data = Schema.Schema.Type<typeof DataSchema>;
