import { Schema } from 'effect';

// Generated schemas for state validation in state.proto
// Source: /Users/nataliai/Projects/test/effect/src/proto/state.proto
// Generated on: 2025-10-05T19:37:00.296Z
// 
// This file includes custom validation for states structure where props cannot be empty.
// DO NOT EDIT THIS FILE MANUALLY - it will be regenerated on build.

export const NativeStateTypeSchema = Schema.Literal(
  'UNKNOWN_NativeStateType',
  'hover',
  'focus',
  'disabled',
  'invalid'
);

// Enhanced schema for states structure validation
// This validates the entire states object structure: states.{key}.props cannot be empty
export const StatesSchema = Schema.Record({
  key: Schema.String,
  value: Schema.Struct({
    displayName: Schema.String,
    props: Schema.Record({
      key: Schema.String,
      value: Schema.Unknown
    }).pipe(Schema.filter((record) => Object.keys(record).length > 0, {
      message: () => "props cannot be empty"
    }))
  })
});

export type States = Schema.Schema.Type<typeof StatesSchema>;
export type NativeStateType = Schema.Schema.Type<typeof NativeStateTypeSchema>;
